### ISSUE TITLE
readthedocs fails (maybe related to PR #202)

### ISSUE THREAD

**Issue by chekos** [executablebooks/MyST-NB#207]
I think this might be related to #202 

MyST-NB works great locally but when I push my changes readthedocs fails. Here's the relevant output:

```
assembling single document... uso/intro uso/faq uso/api uso/generado/nivel-mas-alto/tacosdedatos_utils.manejo_de_archivos uso/generado/nivel-mas-alto/tacosdedatos_utils.manejo_de_proyectos ejemplos/index ejemplos/usando-arbol sobre-tacosdedatos-utils/autores sobre-tacosdedatos-utils/contribuir sobre-tacosdedatos-utils/historia failed

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tacosdedatos-utils/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tacosdedatos-utils/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tacosdedatos-utils/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(['__all__'], to_build)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tacosdedatos-utils/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tacosdedatos-utils/envs/latest/lib/python3.7/site-packages/sphinx/builders/singlehtml.py", line 159, in write
    doctree = self.assemble_doctree()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tacosdedatos-utils/envs/latest/lib/python3.7/site-packages/sphinx/builders/singlehtml.py", line 83, in assemble_doctree
    self.env.resolve_references(tree, master, self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tacosdedatos-utils/envs/latest/lib/python3.7/site-packages/sphinx/environment/__init__.py", line 572, in resolve_references
    self.apply_post_transforms(doctree, fromdocname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tacosdedatos-utils/envs/latest/lib/python3.7/site-packages/sphinx/environment/__init__.py", line 584, in apply_post_transforms
    transformer.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tacosdedatos-utils/envs/latest/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 87, in apply_transforms
    super().apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tacosdedatos-utils/envs/latest/lib/python3.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tacosdedatos-utils/envs/latest/lib/python3.7/site-packages/myst_nb/transform.py", line 54, in apply
    outputs, RENDER_PRIORITY[builder], True, output_dir, None
KeyError: 'readthedocssinglehtmllocalmedia'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/tacosdedatos-utils/envs/latest/lib/python3.7/site-packages/myst_nb/transform.py", line 54, in apply
    outputs, RENDER_PRIORITY[builder], True, output_dir, None
KeyError: 'readthedocssinglehtmllocalmedia'
The full traceback has been saved in /tmp/sphinx-err-zbn6wqtb.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

This only changed when I added a jupyter notebook file to the `docs/` folder.

**Comment by choldgraf** [comment]
hmmm - actually, I think the issue is that the fix there hasn't yet made its way into a release. I'll cut a release now and can you re-try in 5 minutes?

**Comment by chekos** [comment]
![you a real one gif](https://media.tenor.com/images/4f321f89ec1398af00fb50c6c3dcfa0b/tenor.gif)


It worked! thank you so much!

**Comment by choldgraf** [comment]
hooray!
