### ISSUE TITLE
Unexpected keyword argument 'timeout' (update jupyter-cache pin)

### ISSUE THREAD

**Issue by DavidPowell** [executablebooks/MyST-NB#221]
I am compiling a Jupyter Book. I recently updated many of my Jupyter book related python packages, and I now get an error due to an uknown `timeout` keyword when a function is called from myst-nb, as detailed below. I am unsure what function is being called that does not expect the `timeout` keyword.

I found a workaround by downgrading myst-nb to 0.8.0 (I confirmed that the problem occurs on 0.8.2).

I am running under WSL, further environment details are in log file below.

````
# Sphinx version: 2.4.4                                                                                                                              
# Python version: 3.7.7 (CPython)                                                                                                                    
# Docutils version: 0.16 release                                                                                                                     
# Jinja2 version: 2.11.2                                                                                                                             
# Last messages:                                                                                                                                     
#   Running Sphinx v2.4.4                                                                                                                            
#   making output directory...                                                                                                                       
#   done                                                                                                                                             
#   building [mo]: targets for 0 po files that are out of date                                                                                       
#   building [html]: targets for 53 source files that are out of date                                                                                
#   updating environment:                                                                                                                            
# Loaded extensions:                                                                                                                                 
#   sphinx.ext.mathjax (2.4.4) from /home/david/.conda/envs/py37/lib/python3.7/site-packages/sphinx/ext/mathjax.py                                   
#   sphinxcontrib.applehelp (1.0.2) from /home/david/.conda/envs/py37/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py                
#   sphinxcontrib.devhelp (1.0.2) from /home/david/.conda/envs/py37/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py                    
#   sphinxcontrib.htmlhelp (1.0.3) from /home/david/.conda/envs/py37/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py                  
#   sphinxcontrib.serializinghtml (1.1.4) from /home/david/.conda/envs/py37/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py    
#   sphinxcontrib.qthelp (1.0.3) from /home/david/.conda/envs/py37/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py                      
#   alabaster (0.7.12) from /home/david/.conda/envs/py37/lib/python3.7/site-packages/alabaster/__init__.py                                           
#   sphinx_togglebutton (0.2.2) from /home/david/.conda/envs/py37/lib/python3.7/site-packages/sphinx_togglebutton/__init__.py                        
#   sphinx_copybutton (0.3.0) from /home/david/.conda/envs/py37/lib/python3.7/site-packages/sphinx_copybutton/__init__.py                            
#   jupyter_sphinx (0.2.4) from /home/david/.conda/envs/py37/lib/python3.7/site-packages/jupyter_sphinx/__init__.py                                  
#   myst_nb (0.8.3) from /home/david/.conda/envs/py37/lib/python3.7/site-packages/myst_nb/__init__.py                                                
#   jupyter_book (0.7.3) from /home/david/.conda/envs/py37/lib/python3.7/site-packages/jupyter_book/__init__.py                                      
#   sphinxcontrib.bibtex (unknown version) from /home/david/.conda/envs/py37/lib/python3.7/site-packages/sphinxcontrib/bibtex/__init__.py            
#   sphinx_thebe (0.0.7) from /home/david/.conda/envs/py37/lib/python3.7/site-packages/sphinx_thebe/__init__.py                                      
#   sphinxcontrib.video (unknown version) from /mnt/c/Users/dap124/Work Documents/external_code/video/sphinxcontrib/video.py                         
#   sphinxcontrib.youtube (unknown version) from /home/david/.conda/envs/py37/lib/python3.7/site-packages/sphinxcontrib/youtube.py                   
#   sphinx_book_theme (unknown version) from /home/david/.conda/envs/py37/lib/python3.7/site-packages/sphinx_book_theme/__init__.py                  
#   pydata_sphinx_theme (unknown version) from /home/david/.conda/envs/py37/lib/python3.7/site-packages/pydata_sphinx_theme/__init__.py              
Traceback (most recent call last):                                                                                                                   
  File "/home/david/.conda/envs/py37/lib/python3.7/site-packages/jupyter_book/sphinx.py", line 223, in build_sphinx                                  
    app.build(force_all, filenames)                                                                                                                  
  File "/home/david/.conda/envs/py37/lib/python3.7/site-packages/sphinx/application.py", line 349, in build                                          
    self.builder.build_update()                                                                                                                      
  File "/home/david/.conda/envs/py37/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_update                             
    len(to_build))                                                                                                                                   
  File "/home/david/.conda/envs/py37/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 311, in build                                    
    updated_docnames = set(self.read())                                                                                                              
  File "/home/david/.conda/envs/py37/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 382, in read                                     
    for docs in self.events.emit('env-get-outdated', self, added, changed, removed):                                                                 
  File "/home/david/.conda/envs/py37/lib/python3.7/site-packages/sphinx/events.py", line 99, in emit                                                 
    results.append(callback(self.app, *args))                                                                                                        
  File "/home/david/.conda/envs/py37/lib/python3.7/site-packages/myst_nb/cache.py", line 82, in execution_cache                                      
    app.env, exec_docnames, path_cache, app.config["execution_timeout"]                                                                              
  File "/home/david/.conda/envs/py37/lib/python3.7/site-packages/myst_nb/cache.py", line 107, in _stage_and_execute                                  
    execute_staged_nb(cache_base, pk_list or None, timeout)                                                                                          
  File "/home/david/.conda/envs/py37/lib/python3.7/site-packages/myst_nb/cache.py", line 210, in execute_staged_nb                                   
    filter_pks=pk_list or None, converter=path_to_notebook, timeout=timeout                                                                          
TypeError: run_and_cache() got an unexpected keyword argument 'timeout'                                                                              
````

**Comment by chrisjsewell** [comment]
Heya, looks like an outdated version of jupyter-cache, what's the version of that?

**Comment by DavidPowell** [comment]
@chrisjsewell Yes, this somehow seems to be related to this issue. I'm sure that I previously tried updating jupter-cache, but to no avail. I had jupyter-cache 0.2.1 installed when I reported the issue.

I just updated jupyter-cache to 0.3.0 and myst-nb to 0.8.4. It appears to have solved the issue. However, it does give a warning message:

`myst-nb 0.8.4 requires jupyter-cache~=0.2.1, but you'll have jupyter-cache 0.3.0 which is incompatible.`

So I'm confused as to which version of jupyter-cache I should be using.

**Comment by chrisjsewell** [comment]
Yeh looks like the jupyter-cache requirement wasn't updated to https://github.com/executablebooks/jupyter-cache/releases/tag/v0.2.2 where timeout was added.
But anyway they'll be a new release soon, updating to v0.3 😄

**Comment by chrisjsewell** [comment]
version 0.8.5 release 😄 https://github.com/executablebooks/MyST-NB/blob/master/CHANGELOG.md#085---2020-08-11

**Comment by DavidPowell** [comment]
Thanks @chrisjsewell for the quick fix. I confirm that upgrading myst-nb to 0.8.5 has fixed my problem. I note that this upgrade downgraded my myst-parser from 0.10.0 to 0.9.1, but this does not appear to have caused me any problems.
