### ISSUE TITLE
Including this extension makes the build fail with GitHub action

### ISSUE THREAD

**Issue by DominiqueMakowski** [executablebooks/MyST-NB#399]
### Describe the bug

While it works locally, simply [adding the extension](https://github.com/neuropsychology/NeuroKit/pull/634/commits/14863b91df03d8e44a8799314b8252e10f94f8c3) into the conf.py makes the build fail with [this message](https://github.com/neuropsychology/NeuroKit/runs/6018801640?check_suite_focus=true#step:5:533):

```
[sphinx-action] Running: ['sphinx-build', '-b', 'html', '.', '_build', '--keep-going', '--no-color', '-w', '/tmp/sphinx-log']
Traceback (most recent call last):
  File "/entrypoint.py", line 22, in <module>
    action.build_all_docs(github_env, [os.environ.get("INPUT_DOCS-FOLDER")])
  File "/sphinx_action/action.py", line 152, in build_all_docs
    return_code, annotations = build_docs(github_env.build_command, docs_dir)
  File "/sphinx_action/action.py", line 134, in build_docs
    with open(log_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/sphinx-log'
```

It doensnt explicitly say that the error is related to `myst_nb`, but this appears whenever I add the extension into the list so I am assuming it has some effects downstream.

### Reproduce the bug

See [this commit](https://github.com/neuropsychology/NeuroKit/pull/634/commits/14863b91df03d8e44a8799314b8252e10f94f8c3). The docs is built by [this action](https://github.com/neuropsychology/NeuroKit/blob/website-overhaul/.github/workflows/docs-build.yml)

**Comment by DominiqueMakowski** [comment]
This bug seems to be inconsistent and disapeared when i retriggered the action. Closing this
