### ISSUE TITLE
0.13.2: sphinx fails on generate man page

### ISSUE THREAD

**Issue by kloczek** [executablebooks/MyST-NB#400]
### Describe the bug

**context**
I'm trying to package your module as the rpm package.
Part of that process is building sphinx based documentation as man page (ad on all unixes man page is still most basic forrm of the documentation).

**expectation**
Should be possible to generate `MyST-NB` documentation as man page.

**bug**
First of all looks like docs/copy.py has issue and is not at all generate documentation.
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v4.5.0

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 425, in load_extension
    mod = import_module(extname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'myst_nb'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 428, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension myst_nb (exception: No module named 'myst_nb')

Extension error:
Could not import extension myst_nb (exception: No module named 'myst_nb')
```
This can be solved by below patch:
```patch
--- a/docs/conf.py~     2022-02-10 20:10:25.000000000 +0000
+++ b/docs/conf.py      2022-04-16 15:25:17.398623813 +0000
@@ -12,8 +12,8 @@
 #
 import os

-# import sys
-# sys.path.insert(0, os.path.abspath('.'))
+import sys
+sys.path.insert(0, os.path.abspath('..'))


 # -- Project information -----------------------------------------------------
```
This needs to be added when `myst-nb` module is build in the build env where that module still is not installed (as it is typically on packagin the software).
With that patch however still it is not possible to generate roff output becuse probably something still is not finished in `myst-nb` module.
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v4.5.0
making output directory... done
CoconutWarning: Failed to update Coconut Jupyter kernel installation; the 'coconut' kernel might not work properly as a result (try again with 'sudo').
Coconut: Installing Jupyter kernels 'coconut_py', 'coconut_py2', 'coconut_py3'...
Coconut: Successfully installed Jupyter kernels: 'coconut_py', 'coconut_py2', 'coconut_py3'
myst v0.17.1: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=['amsmath', 'colon_fence', 'deflist', 'dollarmath', 'html_image'], linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], all_links_external=False, url_schemes=['http', 'https', 'mailto', 'ftp'], ref_domains=None, highlight_code_blocks=True, number_code_blocks=[], title_to_header=False, heading_anchors=None, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 256, in __init__
    self._init_builder()
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 315, in _init_builder
    self.events.emit('builder-inited')
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/tkloczko/rpmbuild/BUILD/MyST-NB-0.13.2/myst_nb/__init__.py", line 313, in set_render_priority
    raise MystNbConfigError(f"`nb_render_priority` not set for builder: {builder}")
myst_nb.MystNbConfigError: `nb_render_priority` not set for builder: man

MyST NB Configuration Error:
`nb_render_priority` not set for builder: man
```
Could you pelase have look on that missing part?

### Reproduce the bug

Run `sphinx-build -n -T -b man docs build/sphinx/man` in source tree root.

### List your environment

list of modulesa installed in build env
```console
Package                       Version
----------------------------- -----------------
alabaster                     0.7.12
argon2-cffi                   21.1.0
attrs                         21.4.0
Babel                         2.9.1
backcall                      0.2.0
beautifulsoup4                4.10.0
bleach                        4.1.0
build                         0.7.0
cffi                          1.15.0
charset-normalizer            2.0.12
click                         8.1.2
coconut                       1.6.0
codespell                     2.1.0
cPyparsing                    2.4.7.1.1.0
cycler                        0.11.0
debugpy                       1.6.0
decorator                     5.1.1
defusedxml                    0.7.1
distro                        1.7.0
docutils                      0.17.1
entrypoints                   0.4
extras                        1.0.0
fastjsonschema                2.15.3
fixtures                      3.0.0
fonttools                     4.32.0
gpg                           1.17.1-unknown
greenlet                      1.1.2
html5lib                      1.1
idna                          3.3
imagesize                     1.3.0
importlib-metadata            4.11.3
importlib-resources           5.7.0
iniconfig                     1.1.1
ipykernel                     6.13.0
ipython                       7.30.1
ipython-genutils              0.2.0
ipywidgets                    7.7.0
jedi                          0.18.1
Jinja2                        3.1.1
jsonschema                    4.4.0
jupyter-cache                 0.5.0
jupyter-client                7.2.2
jupyter-core                  4.9.2
jupyter-sphinx                0.3.2
jupyterlab-pygments           0.1.2
jupytext                      1.13.7
kiwisolver                    1.3.2
libcomps                      0.1.18
markdown-it-py                2.0.1
MarkupSafe                    2.1.1
matplotlib                    3.5.1
matplotlib-inline             0.1.3
mdit-py-plugins               0.3.0
mdurl                         0.1.0
mistune                       0.8.4
myst-parser                   0.17.1
nbclient                      0.5.13
nbconvert                     6.4.5
nbformat                      5.3.0
nest-asyncio                  1.5.5
notebook                      6.4.8
numpy                         1.22.3
olefile                       0.46
packaging                     21.3
pandocfilters                 1.5.0
parso                         0.8.3
pbr                           5.8.1
pep517                        0.12.0
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.1.0
pip                           22.0.4
pluggy                        1.0.0
ply                           3.11
prometheus-client             0.14.1
prompt-toolkit                3.0.29
psutil                        5.9.0
ptyprocess                    0.7.0
py                            1.11.0
pycparser                     2.21
Pygments                      2.11.2
PyGObject                     3.42.0
pyparsing                     3.0.8
pyrsistent                    0.18.1
pytest                        7.1.1
python-dateutil               2.8.2
pytz                          2022.1
PyYAML                        6.0
pyzmq                         22.3.0
requests                      2.27.1
rpm                           4.17.0
Send2Trash                    1.8.0
setuptools                    62.0.0
six                           1.16.0
snowballstemmer               2.2.0
soupsieve                     2.3.2.post1
Sphinx                        4.5.0.dev20220404
sphinx-copybutton             0.4.0
sphinx-togglebutton           0.2.3
sphinxcontrib-applehelp       1.0.2.dev20220410
sphinxcontrib-devhelp         1.0.2.dev20220410
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1.dev20220410
sphinxcontrib-qthelp          1.0.3.dev20220410
sphinxcontrib-serializinghtml 1.1.5
SQLAlchemy                    1.4.35.dev0
tabulate                      0.8.9
terminado                     0.13.3
testpath                      0.6.0
testtools                     2.5.0
toml                          0.10.2
tomli                         2.0.1
tornado                       6.1
traitlets                     5.1.1
typing_extensions             4.1.1
urllib3                       1.26.9
wcwidth                       0.2.5
webencodings                  0.5.1
wheel                         0.37.1
widgetsnbextension            3.6.0
zipp                          3.8.0
```

**Comment by chrisjsewell** [comment]
> +sys.path.insert(0, os.path.abspath('..'))
> With that patch however still it is not possible to generate roff output becuse probably something still is not finished in myst-nb module.

This is precisely why inserting packages into the system path, rather than installing is not a good idea, since it does not handle the full installation process, such as loading entry points.

You should be building your package documentation in isolated virtual environments

**Comment by kloczek** [comment]
> This is precisely why inserting packages into the system path, rather than installing is not a good idea, since it does not handle the full installation process, such as loading entry points.

> You should be building your package documentation in isolated virtual environments

This has nothing to do with mani issu which so far not have been commented by you.
Could you pelase have look one more time on that issue?

Other thing is that building documentation in isolated env may be necessary if documenation is using module metadata which is not the case.
