### ISSUE TITLE
myst_parser.sphinx_ext Module not Found

### ISSUE THREAD

**Issue by fccoelho** [executablebooks/MyST-NB#444]
### Describe the bug

**context**
When I run `make html` on my sphinx folder, without the myst_nb enabled in my conf.py, everything compiles nices, but I need to compile Notebooks, so I added Myst-NB. 

**expectation**
I expected everything to continue to work.

**bug**
But instead instead I get the following exception:

```python
# Sphinx version: 4.5.0
# Python version: 3.10.4 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.1.2
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/local/lib/python3.10/dist-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/usr/local/lib/python3.10/dist-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/local/lib/python3.10/dist-packages/sphinx/registry.py", line 438, in load_extension
    metadata = setup(app)
  File "/usr/local/lib/python3.10/dist-packages/myst_nb/__init__.py", line 8, in setup
    from .sphinx_ext import sphinx_setup
  File "/usr/local/lib/python3.10/dist-packages/myst_nb/sphinx_ext.py", line 9, in <module>
    from myst_parser.sphinx_ext.main import setup_sphinx as setup_myst_parser
ModuleNotFoundError: No module named 'myst_parser.sphinx_ext'
```

### Reproduce the bug

This used to work in the past for other projects of mine, so I think this maybe a regression

versions of relevant packages:
myst==1.0.4
myst-nb==0.13.2
myst-parser==0.15.2

I am not using Jupyter-book

**Comment by chrisjsewell** [comment]
Heya, `myst_nb.sphinx_ext` was only added in `myst-nb` `v0.14.0` (in #409) so it seems that is the version you have. In this case, it is compatible with `myst-parser` `v0.17.2`

**Comment by fccoelho** [comment]
Thanks @chrisjsewell ! that fixed it!
