### ISSUE TITLE
path is deprecated.

### ISSUE THREAD

**Issue by Carreau** [executablebooks/MyST-NB#540]
### Describe the bug

I was building scipy docs and got greeted with a 

```
Traceback (most recent call last):
  File "/Users/bussonniermatthias/miniforge3/envs/scipy-dev/lib/python3.11/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/miniforge3/envs/scipy-dev/lib/python3.11/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/Users/bussonniermatthias/miniforge3/envs/scipy-dev/lib/python3.11/site-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/Users/bussonniermatthias/miniforge3/envs/scipy-dev/lib/python3.11/site-packages/sphinx/registry.py", line 472, in load_extension
    metadata = setup(app)
               ^^^^^^^^^^
  File "/Users/bussonniermatthias/miniforge3/envs/scipy-dev/lib/python3.11/site-packages/myst_nb/__init__.py", line 10, in setup
    return sphinx_setup(app)
           ^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/miniforge3/envs/scipy-dev/lib/python3.11/site-packages/myst_nb/sphinx_ext.py", line 98, in sphinx_setup
    add_css(app)
  File "/Users/bussonniermatthias/miniforge3/envs/scipy-dev/lib/python3.11/site-packages/myst_nb/sphinx_ext.py", line 189, in add_css
    with import_resources.path(static, "mystnb.css") as source_path:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/miniforge3/envs/scipy-dev/lib/python3.11/importlib/resources/_legacy.py", line 18, in wrapper
    warnings.warn(
DeprecationWarning: path is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
```

`path()` appear to still be there:

https://github.com/executablebooks/MyST-NB/blob/35ebd5429c1c315d2564af261b4df836651962eb/myst_nb/sphinx_ext.py#L189-L191

### Reproduce the bug

Will try to make a minimal reproducible example, I just want to log the issue before I forget.

**Comment by WarrenWeckesser** [comment]
@Carreau, I just ran into the same issue.  Did you find a work-around for this?

**Comment by WarrenWeckesser** [comment]
FYI: I edited my installed copy of `myst_nb/sphinx_ext.py` using the suggestion in the docstring of the deprecated [`importlib.resources.path`](https://docs.python.org/3/library/importlib.resources.html#importlib.resources.path) and I was able to build the SciPy docs.  Specifically, change each occurrence of

    with import_resources.path(static, "mystnb.css") as source_path:

to

    with import_resources.as_file(import_resources.files(static).joinpath("mystnb.css")) as source_path:

It is a simple change, but it requires at least Python 3.9.

**Comment by agoose77** [comment]
We're tracking this :)
